<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class rekomendasi_terdaftar_yayasan extends Model
{
    public $table = 'rekomendasi_terdaftar_yayasans';
    protected $fillable = [
        'id_alur',
        'no_pendaftaran',
        'id_provinsi',
        'id_kabkot',
        'id_kecamatan',
        'id_kelurahan',
        'jenis_pelapor',
        'nik_ter',
        'nama_ter',
        'tempat_lahir',
        'tgl_lahir',
        'jenis_kelamin',
        'telp',
        'alamat',
        'nama_pel',
        'nik_pel',
        'tempat_lahirpel',
        'tgl_lahirpel',
        'telp_pel',
        'alamat_pel',
        'nama_lembaga',
        'alamat_lembaga',
        'akta_notaris',
        'no_akta',
        'nama_ketua',
        'jenis_kesos',
        'status',
        'wil_kerja',
        'tipe',
        'tgl_mulai',
        'tgl_selesai',
        'file_permohonan',
        'catatan',
        'status_alur',
        'tujuan',
        'petugas',
        'createdby',
        'updatedby'

    ];
    protected $casts = [
        'id_alur'=> 'string',
        'no_pendaftaran'=> 'string',
        'id_provinsi'=> 'string',
        'id_kabkot'=> 'string',
        'id_kecamatan'=> 'string',
        'id_kelurahan'=> 'string',
        'jenis_pelapor'=> 'string',
        'nik_ter'=> 'string',
        'nama_ter'=> 'string',
        'tempat_lahir' => 'string',
        'tgl_lahir'=> 'string',
        'telp'=> 'string',
        'alamat'=> 'string',
        'nama_pel'=> 'string',
        'nik_pel'=> 'string',
        'tempat_lahirpel'=> 'string',
        'tgl_lahirpel'=> 'string',
        'jenis_kelaminpel'=> 'string',
        'telp_pel'=> 'string',
        'alamat_pel'=> 'string',
        'nama_lembaga'=> 'string',
        'alamat_lembaga'=> 'string',
        'akta_notaris'=> 'string',
        'no_akta'=> 'string',
        'nama_ketua'=> 'string',
        'jenis_kesos'=> 'string',
        'status'=> 'string',
        'wil_kerja'=> 'string',
        'tipe'=> 'string',
        'tgl_mulai'=>'string',
        'tgl_selesai'=>'string',
        'file_permohonan'=> 'string',
        'catatan'=> 'string',
        'status_alur'=> 'string',
        'tujuan'=> 'string',
        'petugas'=> 'string',
        'createdby'=> 'string',
        'updatedby'=> 'string'
    ];

    public static array $rules = [
        'id_alur' => 'required',
        'no_pendaftaran' => 'required',
        'id_provinsi' => 'required',
        'id_kabkot' => 'required',
        'id_kecamatan' => 'required',
        'id_kelurahan' => 'required',
        'jenis_pelapor' => 'required',
        'nik_ter' => 'required',
        'nama_ter' => 'required',
        'tempat_lahir'=> 'required',
        'tgl_lahir' => 'required',
        'telp' => 'required',
        'alamat' => 'required',
        'nama_pel'=> 'required',
        'nik_pel'=> 'required',
        'tempat_lahirpel'=> 'required',
        'tgl_lahirpel'=> 'required',
        'jenis_kelaminpel'=> 'required',
        'telp_pel'=> 'required',
        'alamat_pel'=> 'required',
        'nama_lembaga'=> 'required',
        'alamat_lembaga'=> 'required',
        'akta_notaris'=> 'required',
        'no_akta'=> 'required',
        'nama_ketua'=> 'required',
        'jenis_kesos'=> 'required',
        'status'=> 'required',
        'wil_kerja'=> 'required',
        'tipe'=> 'required',
        'tgl_mulai'=>'required',
        'tgl_selesai'=>'required',
        'file_permohonan'=> 'required',
        'catatan' => 'required',
        'status_alur' => 'required',
        'tujuan' => 'required',
        'petugas' => 'required',
        'createdby' => 'required',
        'updatedby' => 'required'
    ];
}
